function medium = acousticPropertiesModified(setting, phan, add_absorption, density, fat_frac)
%ACOUSTICPROPERTIESMODIFIED is  amodified version of Acoustic properties, and create a 3D description of acoustic tissue properties
%
% DESCRIPTION:
%       acousticPropertiesModified creates a 3D volume of the
%       acoustic properties of the tissue, ie. speed of sound and
%       absorption
%
% USAGE:
%       medium = acousticPropertiesModified(setting, phan)
%       medium = acousticPropertiesModified(setting, phan, add_absorption)
%       medium = acousticPropertiesModified(setting, phan, add_absorption, density)
%       medium = acousticPropertiesModified(setting, phan, add_absorption, ...
%                                                        density, fat_frac)
%
% INPUTS:
%       setting    - a struct generated by makePAMMOTHGeometry.m
%       phan       - a breast phantom generated by getBreastPhantom.m
%
% OPTIONAL INPUTS:
%       add_absorption - Boolean controlling whether acoustic absorption is
%                        modeled (default = false)
%       density        - Boolean controlling whether the mass density
%                        should also be modeled inhomogenous (default =
%                        false).
%       fat_fraction   - for generic breast tissue used in the synthetic
%                        phantoms, this value sets the percentage of fat
%                        vs. fibro-glandular tissue to determine the
%                        homogenous acoustic properties of the generic
%                        tissue (default = 0.5)
%
% OUTPUTS:
%       medium - a struct describing the acoustic properties in the format
%                that kWave is using (see kWave manual for more details)
%
% ABOUT:
%       author          - Felix Lucka, Ashkan Javaherian
%       date            - 20.06.2017
%       last update     - 30.11.2018
%
%
% See also acousticProperties, getBreastPhantom, makePAMMOTHGeometry, opticalProperties

% check user defined value for add_absorption, otherwise assign default value
if nargin < 3 || isempty(add_absorption)
    add_absorption = false;
end

% check user defined value for density, otherwise assign default value
if nargin < 4 || isempty(density)
    density = false;
end

% check user defined value for fat_pct, otherwise assign default value
if nargin < 5 || isempty(fat_frac)
    fat_frac = 0.5;
end

% check whether breast phantoms fits into bowl
if(any(phan(:) > 0 & not(setting.mask(:) == 1 | setting.mask(:) == 3)))
   % error('Breast does not fit into bowl')
end

medium = [];

% set speed of sound [m/s]
aux = 1500 * ones(setting.Nxyz); % coupling medium
aux(setting.mask == 3) = 1515; % chest wall
aux(phan == 1) = 1525; % fibro-glandular tissue
aux(phan == 2) = 1470; % fat
aux(phan == 3) = 1584; % skin
aux(phan == 4) = 1550; % blood vessel
aux(phan == 5) = fat_frac * 1470 + (1-fat_frac) * 1525; % generic breast tissue

medium.sound_speed = aux;

if(density)
    
    % set mass density [kg/m^3]
    aux = 1000 * ones(setting.Nxyz); % coupling medium and background
    aux(setting.mask == 3) = 1040; % chest wall
    aux(phan == 1) = 1040;         % fibro-glandular tissue
    aux(phan == 2) = 937;          % fat
    aux(phan == 3) = 1150;         % skin
    aux(phan == 4) = 1040;         % blood vessel
    aux(phan == 5) = fat_frac * 937 + (1-fat_frac) * 1040; % generic breast tissue
    
    medium.density = aux;
    
else
    
    medium.density = 1;
    
end



if (add_absorption)
    
% set attenuation [dB/MHz cm]
aux = zeros(setting.Nxyz);  % coupling medium
aux(setting.mask == 3) = 0; % chest wall
aux(phan == 1) = 0.75;      % fibro-glandular tissue
aux(phan == 2) = 0.6;       % fat 
aux(phan == 3) = 1.0;       % skin
aux(phan == 4) = 0.15;      % blood vessel
aux(phan == 5) = 0.75;      % generic breast tissue

%  attenuation power
medium.alpha_coeff = aux;

end


end